### ISSUE TITLE
Cann't publish message with emqx-web-hook enabled

### ISSUE THREAD

**Issue by RichardChengshaojin** [emqx/emqx-web-hook#201]
I enable emqx-web-hook plugin with the configuration below:

```java
web.hook.api.url = http://10.150.123.214:8080/emqx/hook

web.hook.rule.client.connected.1     = {"action": "on_client_connected"}
web.hook.rule.client.disconnected.1  = {"action": "on_client_disconnected"}
web.hook.rule.client.subscribe.1     = {"action": "on_client_subscribe"}
web.hook.rule.client.unsubscribe.1   = {"action": "on_client_unsubscribe"}
web.hook.rule.session.created.1      = {"action": "on_session_created"}
web.hook.rule.session.subscribed.1   = {"action": "on_session_subscribed"}
web.hook.rule.session.unsubscribed.1 = {"action": "on_session_unsubscribed"}
web.hook.rule.session.terminated.1   = {"action": "on_session_terminated"}
web.hook.rule.message.publish.1      = {"action": "on_message_publish"}
web.hook.rule.message.delivered.1    = {"action": "on_message_delivered"}
web.hook.rule.message.acked.1        = {"action": "on_message_acked"}
```

And I can receive the message in my server:

```java
{"action":"client_disconnected","client_id":"emqx_test_consumer1","username":"radioServer","reason":"closed"}
{"action":"session_terminated","client_id":"emqx_test","reason":"discarded"}
{"action":"session_created","client_id":"emqx_test","username":"radioServer"}
{"action":"client_connected","client_id":"emqx_test","username":"radioServer","conn_ack":0}
{"action":"client_subscribe","client_id":"emqx_test","username":"radioServer","topic":"testtopic/1","opts":{"nl":0,"qos":1,"rap":0,"rc":0,"rh":0}}
{"action":"session_subscribed","client_id":"emqx_test","topic":"testtopic/1","opts":{"first":true,"nl":0,"qos":1,"rap":0,"rc":0,"rh":0}}
```

But, the publishing message function cannot work  with the code below:

```java
client.publish(pubTopic, message); // eclipse paho client 
```

it triggers an Exception:

```java
org.eclipse.paho.client.mqttv3.MqttException: timeout from server
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
	at org.eclipse.paho.client.mqttv3.internal.ClientState.checkForActivity(ClientState.java:694)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.checkForActivity(ClientComms.java:784)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.checkForActivity(ClientComms.java:770)
	at org.eclipse.paho.client.mqttv3.TimerPingSender$PingTask.run(TimerPingSender.java:77)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

How can I solve this  problem with emqx-web-hook enabled ?

**Comment by HJianBo** [comment]
Hi @RichardChengshaojin Will it is blocked in message_publish handling progress? What happened if you disable the `emqx-web-hook`?

**Comment by RichardChengshaojin** [comment]
> Hi @RichardChengshaojin Will it is blocked in message_publish handling progress? What happened if you disable the `emqx-web-hook`?

Hi @HJianBo it works well if I disable the `emqx-web-hook`, I can publish message.

**Comment by RichardChengshaojin** [comment]
> Hi @RichardChengshaojin Will it is blocked in message_publish handling progress? What happened if you disable the `emqx-web-hook`?

And here is my code, just like the example showing in [EQM docs](https://docs.emqx.io/broker/latest/en/development/java.html)

```java
import org.eclipse.paho.client.mqttv3.MqttClient;
import org.eclipse.paho.client.mqttv3.MqttConnectOptions;
import org.eclipse.paho.client.mqttv3.MqttException;
import org.eclipse.paho.client.mqttv3.MqttMessage;
import org.eclipse.paho.client.mqttv3.persist.MemoryPersistence;


public class App {

    public static void main(String[] args) {
        String subTopic = "testtopic/#";
        String pubTopic = "testtopic/1";
        String content = "Hello World";
        int qos = 2;
        String broker = "tcp://broker.emqx.io:1883";
        String clientId = "emqx_test";
        MemoryPersistence persistence = new MemoryPersistence();

        try {
            MqttClient client = new MqttClient(broker, clientId, persistence);

            // MQTT connection option
            MqttConnectOptions connOpts = new MqttConnectOptions();
            connOpts.setUserName("emqx_test");
            connOpts.setPassword("emqx_test_password".toCharArray());
            // retain session
            connOpts.setCleanSession(true);

            // set callback
            client.setCallback(new OnMessageCallback());

            // establish a connection
            System.out.println("Connecting to broker: " + broker);
            client.connect(connOpts);

            System.out.println("Connected");
            System.out.println("Publishing message: " + content);

            // Subscribe
            client.subscribe(subTopic);

            // Required parameters for message publishing
            MqttMessage message = new MqttMessage(content.getBytes());
            message.setQos(qos);
            client.publish(pubTopic, message);
            System.out.println("Message published");

            client.disconnect();
            System.out.println("Disconnected");
            client.close();
            System.exit(0);
        } catch (MqttException me) {
            System.out.println("reason " + me.getReasonCode());
            System.out.println("msg " + me.getMessage());
            System.out.println("loc " + me.getLocalizedMessage());
            System.out.println("cause " + me.getCause());
            System.out.println("excep " + me);
            me.printStackTrace();
        }
    }
}
```

**Callback**:

```java
import org.eclipse.paho.client.mqttv3.IMqttDeliveryToken;
import org.eclipse.paho.client.mqttv3.MqttCallback;
import org.eclipse.paho.client.mqttv3.MqttMessage;

public class OnMessageCallback implements MqttCallback {
    @Override
    public void connectionLost(Throwable cause) {
        // After the connection is lost, it usually reconnects here
        System.out.println("disconnect，you can reconnect");
    }

    @Override
    public void messageArrived(String topic, MqttMessage message) throws Exception {
        // The messages obtained after subscribe will be executed here
        System.out.println("Received message topic:" + topic);
        System.out.println("Received message Qos:" + message.getQos());
        System.out.println("Received message content:" + new String(message.getPayload()));
    }

    @Override
    public void deliveryComplete(IMqttDeliveryToken token) {
        System.out.println("deliveryComplete---------" + token.isComplete());
    }
}
```

Many thanks for your kind help.

**Comment by HJianBo** [comment]
Duplicated: https://github.com/emqx/emqx/issues/3583
